### ISSUE TITLE
Add support for general plotting

### ISSUE THREAD

**Issue by ssaket** [unfoldtoolbox/UnfoldMakie.jl#1]
Provide general plotting functions like from mne.vis

**Comment by behinger** [comment]
- [ ] topoplot series
- [ ] ERPimages
- [x] erp-like plots
    - [ ] Support spline/continuous/predicted coefficients
- [ ] plot designmatrix
     - [ ] time-expanded
     - [x] normal
- [ ] butterfly plots

Did you think of any others?

**Comment by ssaket** [comment]
hmm. Maybe some util plots like `plot_cov, plot_csd`, I can't think of anything else.
