### ISSUE TITLE
rename plot_circulareegtopoplot to smth more senseful

### ISSUE THREAD

**Issue by vladdez** [unfoldtoolbox/UnfoldMakie.jl#104]
for instance:
- topoplot_circular
- circular_topoplot

**Comment by vladdez** [comment]
and moreover it is not eeg, but erp topoplot

**Comment by behinger** [comment]
you can topoplot non-erp data as well, e.g. alpha-activity or something

**Comment by vladdez** [comment]
circular_topoplot then - it also written in our main page

**Comment by behinger** [comment]
I dont understand, you mean rename to
plot_circular_topoplot?

**Comment by vladdez** [comment]
Yes

**Comment by behinger** [comment]
fine with me
