### ISSUE TITLE
no explanation for arguments in plotconfig

### ISSUE THREAD

**Issue by vladdez** [unfoldtoolbox/UnfoldMakie.jl#106]
The arguments which come up in the fields Shared Configuration Options - their functionality is not explained anywhere (not even in docs). It should be definitely explained in docstrings.

**Comment by behinger** [comment]
can you provide more information on what you mean? I cannot find "shared configuration options" anywhere

**Comment by vladdez** [comment]
![image](https://github.com/unfoldtoolbox/UnfoldMakie.jl/assets/33777074/7a3fa25e-2e55-41fb-9bf5-4cc1d6b8453b)
Imagine I would like to used plot_designmatrix() 
But I can not find anywhere a docstring or documentation page about arguments from Shared Configuration Options.
For instance, xlabelFromMapping (actaully what does it?).

**Comment by behinger** [comment]
ah I see. So you are missing documentation for the subfields of the shared options.

Yeah, we can create one and link it - putting them in each functions docstring probably too much. But we could put them in e.g. ?plotconfig or something

**Comment by vladdez** [comment]
Yep! How it will works then?

**Comment by behinger** [comment]
you could provide documentation in the docstring of PlotConfig - or maybe better use something lke
```julia
"""
- X => Bla
- Y => Blub
"""
configoptions() = "the docstring to this function reveals documentation to all options pre-specified via in PlotConfig"
```

**Comment by vladdez** [comment]
Conclusion:
- write to mapping - "Use any mapping from AOG"
- deprecate `show_legend`
- check that all lines have links

**Comment by vladdez** [comment]
#237
