### ISSUE TITLE
plot_topoplotseries - contour levels are overwritten

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/UnfoldMakie.jl#120]
there is a bug here:
https://github.com/unfoldtoolbox/UnfoldMakie.jl/blob/3025598659ac4f405457502a20b6beae1968669c/src/eeg_series.jl#L120

if one specifies the contour manually, then it is overwritten by automatic contour-levels. 
E.g: 
```
h = plot_topoplotseries(eff_mult, 0.15; positions = pos2d,
visual = (;enlarge=0.9,
label_scatter=false,    
contours=(linewidth=1, color=:black))) 
```

Reason is that this merge doesnt merge tuples within tuples. Thus a special merge needs to take place here, explicitly for contour

**Comment by vladdez** [comment]
i checked it and i don't see any problem here: contours are perfectly drawn. Seems like issue is outdated

**Comment by vladdez** [comment]
`@testset "contours" begin
    plot_topoplotseries(
        df;
        bin_width,
        positions = positions,
        visual = (; enlarge = 0.9,
        contours = (; linewidth = 1, color = :black)),
    )
end

@testset "contours" begin
    plot_topoplotseries(
        df;
        bin_width,
        positions = positions,
        visual = (; enlarge = 0.9,
        contours = (; linewidth = 5, color = :blue)),
    )
end`

one was black, another blue, size was different

**Comment by behinger** [comment]
no, with custom levels included, levels mean where exactly the contours are in terms of voltage

**Comment by vladdez** [comment]
```
(q_min, q_max) = (-0.1, 0.9)
           plot_topoplotseries(
               df;
               bin_width,
               positions = positions,
               visual = (; enlarge = 0.9, contours = (; linewidth = 1, color = :black, 
               levels = range(q_min, q_max; length = 7))),
           )
┌ Debug: (linewidth = 1, color = :black, levels = -0.1:0.16666666666666666:0.9)
```

bug or feature?

**Comment by behinger** [comment]
I dont understand what youmean with bug or feature because I dont know the output
can you manually input levels = [0,0.5] and do you then have only 2 contour lines visible? do they have linewidth 1 nd :black?

I expected levels to be part of `visual.contours`  as in the code

**Comment by vladdez** [comment]
I meant is that expected or not.

Okay I understood that i didn't understand this parameter. 

I looked in MNE: there is a parameter contour and it is Integer, default number is 6.
If I put any integer in visual.contours.levels the number of lines will change. By default it is 6 too.

I dont understand why is it `contours = (; levels = range(q_min, q_max; length = 7))` in eeg_series.jl (it is ignored anyway though) and why you want to put input  `levels = [0,0.5]` (it will be one line btw).

**Comment by vladdez** [comment]
ah okay, it could be array too

so if I manually specify it, it will change, if not - it will be 6.

**Comment by vladdez** [comment]
But what was the goal? 
To overwrite lelvels manually? Then it works already
To make them dependable on q_min, q_max? That is not working currently

**Comment by behinger** [comment]
No, to make the levels specifiallble via Array, but at the same time be able to change their appearance.

**Comment by vladdez** [comment]
in that case it work already

**Comment by behinger** [comment]
awesome! I dont really understand how it is possible but good then :-)

**Comment by behinger** [comment]
thanks for looking into it!
