### ISSUE TITLE
circular topoplot - label not working

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/UnfoldMakie.jl#123]
![5b95213d](https://github.com/unfoldtoolbox/UnfoldMakie.jl/assets/10183650/2b4bffd5-5a1c-42dd-9f6f-366593dd3d41)
the label in the center is currently not working

**Comment by vladdez** [comment]
These also do not work
```
axis = (; label = "Time?!"), 
 labels = labels,
```

**Comment by vladdez** [comment]
solved in fix #166
