### ISSUE TITLE
topoplot interpretation label

### ISSUE THREAD

**Issue by vladdez** [unfoldtoolbox/UnfoldMakie.jl#129]
We asked in a survey about time interpretation on topoplot and topoplot timeseries´, but don't have any ways to put that on a plot yet. Should be added.

**Comment by vladdez** [comment]
hm, oaky but do we have a way to switch between the modes? There should two modes: time point or average of time interval. Ideally it should be through one argument.

**Comment by behinger** [comment]
mh that feature is not yet implemented. it is very easy to implement though. You could just use the following `combinefun` :

```julia
eeg_topoplotseries(...,combinefun = x->x[end÷2])
```

**Comment by vladdez** [comment]
selects the middle element - is it the median?

will eeg_topoplotseries(...,combinefun = median) five the same result?

**Comment by vladdez** [comment]
and of course it should show one number, not the interval

**Comment by vladdez** [comment]
also we need such option of a single topoplot.

**Comment by vladdez** [comment]
1. I tried and see no difference visually (and theoretically tbh)
2. ok
3. for reproducibility! looking at a single topoplot I want to know what it shows me: a single time point (and which one exactly), mean over all time points (or some time interval), what is the time interval used (sec or msec). If we are advocating for label specification everywhere we should strict ourselves.

**Comment by behinger** [comment]
between median, mean and selecting the middle value?

3. I cant think of a good interface, what exactly do you propose?

**Comment by vladdez** [comment]
basically the same as in a topoplot series: a title with a single number or time interval under the topoplot

**Comment by vladdez** [comment]
![image](https://github.com/unfoldtoolbox/UnfoldMakie.jl/assets/33777074/291f4bf7-9750-4fff-b262-e234a21fd2ad)

**Comment by behinger** [comment]
2. no,  the result is clear, but the interface, how you call plot_topoplot differently.
1. for mean, median and middle value the result might look similar in smooth data, but it is extremely unlikely that they are the same

**Comment by behinger** [comment]
1. missunderstanding, how should we call the plot_topoplot signature differently, e.g. also offer combinefun?
2. exactly, the median is fo the sorted/ordered vector, which is not the case for choosing the midlevalue (a single sample)

**Comment by vladdez** [comment]
1. actually that is a hard question. A partial solution could be just enable opportunity to manually specify xlabel 
2. okay
