### ISSUE TITLE
docstrings formatting is not unified

### ISSUE THREAD

**Issue by vladdez** [unfoldtoolbox/UnfoldMakie.jl#130]
The formatting of docstrings is very different.
For instance:
- `f::Union{GridPosition, GridLayout, Figure}`: Figure, GridLayout or GridPosition that the plot should be drawn into.
- `labels` (default: `nothing`) - channel labels.

We should find a way how to format and show default, possible format and text with explanations in a single format.

**Comment by behinger** [comment]
while I agree, this is lowest priority for me. I'd first go for completion of docstrings

**Comment by vladdez** [comment]
what do you mean by "completion of docstrings"?

**Comment by behinger** [comment]
docs covering all features / kwargs + common issues - we are getting there :)

**Comment by vladdez** [comment]
absolutely agree!
