### ISSUE TITLE
Outdated Zenodo DOI in the README.md

### ISSUE THREAD

**Issue by jschepers** [unfoldtoolbox/UnfoldMakie.jl#132]
If one clicks on the "DOI" button in the README the link leads to an older package version on Zenodo.
Links to: https://zenodo.org/records/6531996 -> version v0.1.4 although the newest version is currently v0.4.0 (https://zenodo.org/records/10235220).

**Comment by vladdez** [comment]
the problem is wider though
it would greate to automatically update it alll the time
