### ISSUE TITLE
Links in the API entries in the documentation do not work

### ISSUE THREAD

**Issue by jschepers** [unfoldtoolbox/UnfoldMakie.jl#139]
When I click on the links in the API entries in the documentation, I get a `404 error` i.e. file not found. 
https://unfoldtoolbox.github.io/UnfoldMakie.jl/dev/api/

**Comment by behinger** [comment]
Here is some useful discussion: https://github.com/JuliaDocs/Documenter.jl/issues/688

It is not possible to link right now as we try it. There is the idea of https://github.com/JuliaDocs/DocumenterInterLinks.jl but it requires the target library to have this as a dependency. Which makie/aog doesnt have

**Comment by vladdez** [comment]
The issue is solved - I put direct links.
