### ISSUE TITLE
Create indicator for topoplot

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/UnfoldMakie.jl#147]
I had trouble to generate such a plot with plot_topoplot

![grafik](https://github.com/unfoldtoolbox/UnfoldMakie.jl/assets/10183650/462b29b6-fc46-49cf-8d55-d1ba4677e68f)

And that plot is ugly. I now used TopoPlots directly.
```
	d = zeros(128)
	d[ch_ix] = 10
	#UnfoldMakie.eeg_matrix_to_dataframe(d,1:128)
	
UnfoldMakie.eeg_topoplot(d;positions=pos,interpolation=UnfoldMakie.TopoPlots.NullInterpolator(),        label_scatter=(;markersize=20)
)
```
it should be super easy to make this plot, maybe even an extra unfoldMakie function - do you remember that I asked you to make that plot clickable and it returns an observable? That would do the trick here perfectly and would be very convenient

**Comment by behinger** [comment]
Probably I could improve it by providing a better colormap - but yeah I was annoyed I couldnt put a non-dataframe into plot_topoplot in the first place :/

**Comment by vladdez** [comment]
as I understand the clickability is the main feature here, right?

**Comment by behinger** [comment]
for me is having a convenient indicator topoplot function

**Comment by behinger** [comment]
```
begin
	function topoplot_indicator!(f,ix)
x = zeros(128)
	x[ix] =1
	clist = [:gray,:darkred][Int.(x.+1)]
		ax = f[1,1] = Axis(f, width = Relative(0.4),
            height = Relative(0.4),
            halign = 1.2,
            valign = 1,aspect=1)
UnfoldMakie.TopoPlots.eeg_topoplot!(ax, x; positions=pos, enlarge=0.9,label_scatter=(;color=clist,markersize=((x.+0.25).*40)./5,strokewidth=0),interpolation=UnfoldMakie.TopoPlots.NullInterpolator())
		hidespines!(ax)
		hidedecorations!(ax)
	end
	
end
```
