### ISSUE TITLE
Nice looking topoplot arrangement

### ISSUE THREAD

**Issue by vladdez** [unfoldtoolbox/UnfoldMakie.jl#156]
We need to implement topoplot series arranging in a nice-looking grid without faceting

**Comment by behinger** [comment]
can you elaborate what you mean here?

**Comment by vladdez** [comment]
When we have a lot of topoplots at some points they should be arranged as a grid. Instead they are just collected in a single row each becoming invisibly small.

**Comment by vladdez** [comment]
fixed in #186
