### ISSUE TITLE
List of useful "snippets"

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/UnfoldMakie.jl#16]
These should likely be in the documentation, but I dont have time right now

## calculate models for multiple subjects; concatenate results
```julia

# results = coeftable(model)
results = DataFrame()
for sub = 1:nsub
        res_s = coeftable(fit(UnfoldModel,...)) # per subject fit
	res_s[!,:subject] .= subj
	append!(results,res_s)
end
```
## calculate ERP over subjects
```julia
using StatsBase # for mean
using DataFramesMeta 
# results => see above
erps = @by(results,[:channel,:time,:coefname],:estimate=mean(:estimate)) # calculate mean over all other dimensions except the given 
plot_results(@subset(erps,:channel .==1)) # select single channel
# you could also select the channel(s) before and then drop the :channel in the @by to average over channels as well
```

**Comment by behinger** [comment]
## single predictor, multiple subjects AoG recipe
data(	@subset(results_all,:basisname .== "other")
)*mapping(:time,:estimate,color=:subject=>nonnumeric,layout=:coefname=>nonnumeric)*visual(Lines)|>draw#plt->draw(plt, legend=(position=:top,)=>nonnumeric)

![grafik](https://user-images.githubusercontent.com/10183650/169480233-0a8fa007-ed6a-4e6c-9500-49d9c9981de8.png)

**Comment by vladdez** [comment]
I tried this: 
`   results = DataFrame()
    nsub = 12
    for sub = 1:nsub
            res_s = coeftable(m) # per subject fit
        res_s[!,:subject] .= sub
        append!(results, res_s)
    end
    
    plot_erp(results; mapping = (; 
    color = :subject, group = :subject, col = :coefname))`

And the result was:
![image](https://github.com/unfoldtoolbox/UnfoldMakie.jl/assets/33777074/13dcb8dd-9119-4615-938e-012e96667e55)
Is that what was intended?
