### ISSUE TITLE
Line-Plots

### ISSUE THREAD

**Issue by SorenDoring** [unfoldtoolbox/UnfoldMakie.jl#18]
They have some presentation problems
- [x] legend placement
- [x] Continuus line for multiple Channels
- [x] Support Butterfly-Plots

"Especially customizing different aspects of the plot, clever designs"

**Comment by behinger** [comment]
- [ ]  legend on / off
- [ ] colorbar(s) on / off
- [ ] free specification of the underlying AoG inputs (cols, rows, color, group, etc. - as good as reasonably possible)
- [ ] (once TopoPlots.jl exists) add an inset marking the plotted channel(s)
![grafik](https://user-images.githubusercontent.com/10183650/169894259-3bd23fc3-24a4-4f26-a360-f1a79e315110.png)

### have to think about this one
- [ ] make it possible to aggregate (e.g. if I put in multiple channels, but dont want a butterfly, it should average

**Comment by behinger** [comment]
- [ ] minor: remove the box of the plot, e.g.: 
![grafik](https://user-images.githubusercontent.com/10183650/170988527-64ce2877-cc27-409a-9a63-682174cf95f1.png)
This follows more towards Tuftes ideas of optimizing Ink-to-data ratio :)
