### ISSUE TITLE
plot_butterfly: expose all configuration options for topoplot

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/UnfoldMakie.jl#183]
It would be great, if we could just add custom options to the butterfly topoplot inset

**Comment by vladdez** [comment]
I added topohalign, topovalign, topoaspect
Anything else?

**Comment by vladdez** [comment]
How it should be implemented? this way? 
![image](https://github.com/unfoldtoolbox/UnfoldMakie.jl/assets/33777074/99031855-68a8-4917-aeb5-128bd1434f29)

**Comment by behinger** [comment]
Yes! The defaults could be pushed to plotconfig

**Comment by vladdez** [comment]
#237 at least infrastructure is implemented
