### ISSUE TITLE
MIsamatch in length between number of trials and sortvalue

### ISSUE THREAD

**Issue by vladdez** [unfoldtoolbox/UnfoldMakie.jl#200]
What should happen when number fo trials and length of sortvalue do not match in erpimage?
Should we allow that or not?

For instance, size of the erp dataset (769, 2508), which means 2508 trials
length of sorting varaible is only 769

**Comment by behinger** [comment]
no, because we dont know which trial matches which sortvalue index

**Comment by vladdez** [comment]
so it should be error message even if the difference is 1 row?

**Comment by behinger** [comment]
I dont see a reason why not

**Comment by vladdez** [comment]
fixed in #199
