### ISSUE TITLE
topoplotseries spacing

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/UnfoldMakie.jl#221]
I think we should add the following info to the docs

To make the spacing of the topoplots more "tight" one has to modify two parameters:
```julia
with_theme(colgap=5) do 
	plot_topoplotseries!(f[2,3],df,0.1;positions=pos,
		axis=(;xlim_topo =(-0.05,1.05),ylim_topo=(-0.05,1.05)))
	end
```
Theoretically, colgap!(f,5) should work as well - but not if you subplot like I do in the example - not even if you generate a GridLayout before, because if I do f[2,3].layout I receive the global layout again and I do not know how to go from a `GridPosition` to a `GridLayout` (maybe you know?)

Note also that I think xlim_topo is deprecated, but I didnt dare to update that plot to a new version ;-) I think it should be `topoplot_axes=(;xlim = (-0.05,1.05))` etc.

**Comment by vladdez** [comment]
fixed in #219
