### ISSUE TITLE
flipped legend labels

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/UnfoldMakie.jl#222]
![grafik](https://github.com/user-attachments/assets/1545e02e-8512-4abe-b953-846f5673fce4)

not sure why the legend labels are once from the left and once from the right :shrug:

**Comment by vladdez** [comment]
colorbar.labelrotation = -π / 2 in plotconfig is responsible for that

**Comment by vladdez** [comment]
let's change make it uniform in `plotconfig`

**Comment by vladdez** [comment]
#237
