### ISSUE TITLE
Contradiction in plot_topoplot signature

### ISSUE THREAD

**Issue by vladdez** [unfoldtoolbox/UnfoldMakie.jl#227]
Why I see this error
```
julia>     plot_topoplot(dat[:, 50, 1])
ERROR: AssertionError: No positions found, did you forget to provide them via positions=XX, or labels=YY?
```
if according to signature positions are kwargs `plot_topoplot(data; positions = nothing, labels = nothing, kwargs...)`?
Some logical error here

**Comment by vladdez** [comment]
#219

**Comment by behinger** [comment]
A comment form the off: this behavior mimicks topoplots.jl behavior where positions is a positional argument as well.

If we change it here, we could also change it there. There reason it is not one in topo plots.jl, is that the second positional argument is "labels",  not sure we support the labels still?

**Comment by behinger** [comment]
So right now you should be able to do:

`plot_topoplots(data;positions=pos)`
or
`plot_topoplot(data;labels=labels)`

Whereas in TopoPlots.jl afaik the interface is crap:
`eeg_topoplot(data::Vector{<: Real}, labels::Vector{<: AbstractString})`

and you have to provide dummy labels if you don't have them (which I think should change - but communication there is a difficult to say the least).

Now we could say we want to have positions as a positional argument, but I dont see the reason why

**Comment by vladdez** [comment]
So there are only two options:
1. we adjust to signature in TopoPlots.jl
2. Topoplots.jl will change their signature

Which is better then?
P.S. of course we can keep it as it is, but it is will be just a source of constant errors.

**Comment by behinger** [comment]
I thought about it again: I really think labels as keyword and positions as positional is the best way to go.

I will make a PR for TopoPlots.jl
