### ISSUE TITLE
Contradiction in signature of plot_topoplotseries 

### ISSUE THREAD

**Issue by vladdez** [unfoldtoolbox/UnfoldMakie.jl#229]
```
julia>     plot_topoplotseries(df; bin_num = 5)
ERROR: AssertionError: No positions found, did you forget to provide them via positions=XX, or labels=YY?
```
So position is args now, not kwargs?

**Comment by behinger** [comment]
I vote no, because you can provide labels (via 10-20systrm) or positions. So positions can be optional.

But more once I'm back from Vacation

**Comment by vladdez** [comment]
okay, then we need to put some dummies instead of positions, right?
