### ISSUE TITLE
plot_erp legend problem

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/UnfoldMakie.jl#234]
I'm currently getting super werid legends, e.g.
![grafik](https://github.com/user-attachments/assets/bef35fc8-da80-4e0c-a5e3-6df2ee73080b)

![grafik](https://github.com/user-attachments/assets/63f96763-eabd-45ec-9790-dd1a159e5a2b)

**Comment by vladdez** [comment]
which version? probably should be solved in a new update
would be also nice to have MWE

**Comment by vladdez** [comment]
Should be resolved in #237
