### ISSUE TITLE
make UM.jl independant from Unfold.jl

### ISSUE THREAD

**Issue by vladdez** [unfoldtoolbox/UnfoldMakie.jl#246]

**Comment by behinger** [comment]
will you do it, or should I?

**Comment by vladdez** [comment]
I think you know better how to do it, so I would suggest you will do it

**Comment by vladdez** [comment]
btw what exaclty being independent means?

**Comment by behinger** [comment]
that it is not needed to be loaded when loading UnfoldMakie. E.g. Project.toml doesnt contain Unfold anymore - we'd use a package extensions, e.g. https://github.com/pebeto/julia_extensions_example

**Comment by vladdez** [comment]
Should it be done this way? or i need to copy functions form Unfold and paste them in this file?
![image](https://github.com/user-attachments/assets/19b24f90-1b81-4dc6-b291-8f21b1f85cb5)

**Comment by behinger** [comment]
yeah, all functions need to go there, but you could do `include(blabla.jl)` same as in UnfoldMakie module

**Comment by behinger** [comment]
What also needs to be added is a kind of "dummy" plot_designmatrix, because extensions cannot export new functions as far as I know
