### ISSUE TITLE
Compatibility with Makie

### ISSUE THREAD

**Issue by vladdez** [unfoldtoolbox/UnfoldMakie.jl#34]
Makie has a new version and because of compatibility issues with UNfold Makie I cannot update.
![image](https://user-images.githubusercontent.com/33777074/207304512-39193e97-2dc1-486b-9ed3-2fd1e2cd0d6a.png)

**Comment by behinger** [comment]
can you prepare a pull?
just add makie 0.19 to compat entry e.g "0.18,0.19"
and bump the version patch +1
