### ISSUE TITLE
Non-Linear Plot

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/UnfoldMakie.jl#36]
It would be great to get have a function/recipe

`plot_splineConfig(m::UnfoldModel;kwargs..)`

that returns a plot like this:
![grafik](https://user-images.githubusercontent.com/10183650/208884914-b84dbd7d-32a9-4c86-884d-0e8c33e462d5.png)

for each spline predictor

**Comment by vladdez** [comment]
https://unfoldtoolbox.github.io/Unfold.jl/dev/generated/explanations/nonlinear_effects/

**Comment by vladdez** [comment]
added in #237
