### ISSUE TITLE
plot_erp continuous colormap + categorical => mixup

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/UnfoldMakie.jl#38]
![grafik](https://user-images.githubusercontent.com/10183650/213810643-6f68e067-10e3-4223-a4c8-855860fc0a05.png)
the legend shouldnt look like this 🤷

**Comment by jschepers** [comment]
**Workaround to separate legend and colorbar:**
```julia
f = plot_erp(effects(Dict(:condition => ["car", "face"], :continuous => -5:5), m);
        mapping=(:color => :continuous, linestyle=:condition, group=:continuous),
        legend = (; valign=:top, halign=:right, tellwidth = false),
        categorical_color=false)

legend = f.content[2]
f[:,1] = legend
```
**Resulting plot**:
![grafik](https://github.com/unfoldtoolbox/UnfoldMakie.jl/assets/22366977/70171891-aec1-4bdb-a72b-e5197542522f)


**Suggestions**:
1. Implement `legend_position` and `colorbar_position` as separate optional arguments of the form `f[:,1]`.
2. Adapt default to not set the exact same position for legend and colorbar but to divide the space in two subspaces [1,1] and [2,1] such that the legend is above the colorbar.

@behinger commented: If we do not come up with anything better we should implement both suggestions.
