### ISSUE TITLE
CircularTopoplots: replace RelativeAxis with width=relative, halign

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/UnfoldMakie.jl#49]
I'm not sure why we made it so complicated to get a relative BBox,

I might miss something, but this should do the trick as well?
```
ax2 = Axis(f[1,1], width=Relative(0.2), height=Relative(0.3), halign=0.1, valign=0.1, backgroundcolor=:white)
```

**Comment by vladdez** [comment]
What exactly do you want to change? 
This: eeg_axis = RelativeAxis(f, rect; xlabel = labels[i], aspect = 1)

**Comment by behinger** [comment]
yes, remove all references to relativeaxis simply by the Relative statement.

**Comment by vladdez** [comment]
okay, how to get the coordinates for each topoplot
Now they are all at the same coordinates
![image](https://github.com/unfoldtoolbox/UnfoldMakie.jl/assets/33777074/6e4b1fd6-5b7e-46ef-aa9e-9d9073a5efe6)

**Comment by behinger** [comment]
not sure I understand your question, the same way as with relative axis I'd assume?

**Comment by vladdez** [comment]
update:
I tried this code and this is the result
```b = rel_to_abs_bbox(f.scene.viewport[], rect)
        eeg_axis = Axis(
            get_figure(f);
            bbox = b,
            xlabel = labels[i],
            aspect = 1,
            width = Relative(1),
            height = Relative(1),
            #halign = -15.5,
            #valign = 1.1,
            backgroundcolor = :white,
        ) 
 ```


![image](https://github.com/unfoldtoolbox/UnfoldMakie.jl/assets/33777074/10c1c2c5-8fbc-44b1-8ebe-29c128f8d4f4)
Kinda works, but shifted to the side for some reason

**Comment by behinger** [comment]
the point being to not use bbox

**Comment by behinger** [comment]
and use width / heigth relative for the placement

**Comment by vladdez** [comment]
The problem is how to get the correct coordinates for topoplots

**Comment by behinger** [comment]
you should be able to extract it frm the bbox

**Comment by vladdez** [comment]
I got it! The shift happened because of colorbar

**Comment by vladdez** [comment]
all tests are good except this - you still can see a slight shift
![image](https://github.com/unfoldtoolbox/UnfoldMakie.jl/assets/33777074/3abac469-be2d-44f6-974c-d87625aca0a7)
