### ISSUE TITLE
Bug: errorribbon not dislayed correctly

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/UnfoldMakie.jl#55]
![image](https://github.com/unfoldtoolbox/UnfoldMakie.jl/assets/10183650/8229b22e-2bed-49a2-868c-1296ccd40724)
my guess is that we push the visual stuff only to lines, but not to ribbon

**Comment by vladdez** [comment]
is there a minimal code example to recreate this figure?

**Comment by vladdez** [comment]
fixed in #237
