### ISSUE TITLE
update the figure on the main page

### ISSUE THREAD

**Issue by vladdez** [unfoldtoolbox/UnfoldMakie.jl#69]
People judge on a first look and figure on the first page is not the best. Moreover it is outdated. Would be great to update it. It is just a png (or whatever) should be easy/ Even my combined plot could be a solution.

**Comment by behinger** [comment]
yes absolutely! we can also do a single plot and the big plot below, or we could do a animation :-)

**Comment by behinger** [comment]
can you do it?
