### ISSUE TITLE
fix parallel plot

### ISSUE THREAD

**Issue by vladdez** [unfoldtoolbox/UnfoldMakie.jl#74]
Smth really wrong happens here in documentation:

![image](https://github.com/unfoldtoolbox/UnfoldMakie.jl/assets/33777074/dddbea03-49bb-4cc6-ac03-5a62288f5964)

**Comment by behinger** [comment]
haha, oh dear - what happened there..

**Comment by behinger** [comment]
probably the Figure() without a f[1,1] is the problem

**Comment by vladdez** [comment]
This problem was fixed
