### ISSUE TITLE
plot_topoplotseries silently ignores Axis 

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/UnfoldMakie.jl#90]
We never actually loop the axis kw-argument through to the axis function.

**Comment by vladdez** [comment]
@behinger could you please clarify this issue? I do not understand what to change here and what is the problem

**Comment by behinger** [comment]
I think the issue back then was that if you modified the axis=(;) in any way it didn't have a result because it was never used in the axis functuon

**Comment by vladdez** [comment]
checked today, all fine
